### PR TITLE
Update TestParse.cs

### PR DESCRIPTION
**Pull request by armin-subasic**

### CODE REVIEW

**Comment by armin-subasic** [comment]
[ExpectedException(typeof (Exception))] is giving a lot of people errors and build failures in Unity.

**Comment by HenrikPoulsen** [comment]
Care to clarify? Is it not throwing exceptions as the tests expect anymore?

**Comment by armin-subasic** [comment]
I know this is a feature for tests, but if tests will make the game unbuildable and will throw errors when there are no errors that then isn't a feature right? Unity will say that expectedexception does not exist

**Comment by HenrikPoulsen** [comment]
Well the tests are not supposed to be compiled when a player gets built. Since that is an editor only folder.
Can you share how to reproduce this issue? What editor version do you have and what platform are you building for?

**Comment by armin-subasic** [comment]
The editor version is 2020.3.20f1 
Platform is IOS
image

**Comment by armin-subasic** [comment]
When it comes to reproducing I literally just imported the scripts in the editor folder...

**Pull request closed without merging**
